# Generated by Django 5.1.1 on 2025-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheepCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sheep_category_name', models.CharField(max_length=100, verbose_name='种类名称')),
                ('sheep_category_image', models.CharField(max_length=255, null=True, verbose_name='种类图片')),
                ('sheep_category_address', models.CharField(max_length=800, verbose_name='地址区域')),
                ('create_time', models.DateField(max_length=100, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'sheep_category',
            },
        ),
    ]
