# Generated by Django 5.1.1 on 2025-02-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sheepcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheepcategory',
            name='sheep_category_image',
        ),
    ]
