# Generated by Django 5.1.1 on 2025-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_sheepcategory_sheep_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='avatar',
            field=models.CharField(max_length=255, null=True, verbose_name='用户头像'),
        ),
    ]
