# Generated by Django 5.1.1 on 2025-02-12 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_sysuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sheep_id', models.CharField(max_length=255, verbose_name='羊只编号')),
                ('sheep_sex', models.SmallIntegerField(choices=[(1, '公羊'), (2, '母羊')], verbose_name='羊只性别')),
                ('sheep_age', models.IntegerField(default=0, verbose_name='羊龄')),
                ('health_condition', models.SmallIntegerField(choices=[(1, '健康'), (2, '良好'), (3, '患病'), (4, '其他')], verbose_name='健康状况')),
                ('horse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sheepcategory', verbose_name='羊只种类')),
            ],
        ),
    ]
