# Generated by Django 5.1.1 on 2025-02-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_sheep'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sheep',
            table='sheep',
        ),
    ]
