# Generated by Django 5.1.1 on 2025-02-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_sheep_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheep',
            old_name='horse_type',
            new_name='sheep_type',
        ),
    ]
